// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eorsdlhbakeqdzcdmbvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvcnNkbGhiYWtlcWR6Y2RtYnZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTYwMDYsImV4cCI6MjA2MDUzMjAwNn0.v1i18L7NM3-QbWSJzPpTHSC7Lc3I7NmJIRxFflnbVNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);